name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - uses: ./.github/actions/docker_up

    - name: Analyzing the code with pylint
      run: |
        scripts/setup/docker_exec.sh pylint $(git ls-files '*.py') --fail-under 9.5

    - uses: ./.github/actions/docker_down
