name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - uses: ./.github/actions/docker_up

    - name: Installing pytest
      run: |
        scripts/setup/docker_exec.sh pip install pytest

    - name: Testing the code
      run: |
        scripts/setup/docker_exec.sh pytest tests

    - uses: ./.github/actions/docker_down
